/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillRouteImport } from './routes/_layout/skill'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutIronclawRouteImport } from './routes/_layout/ironclaw'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAdminRouteImport } from './routes/_layout/_admin'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutEventsIndexRouteImport } from './routes/_layout/events/index'
import { Route as LayoutBuildersIndexRouteImport } from './routes/_layout/builders/index'
import { Route as LayoutAppsIndexRouteImport } from './routes/_layout/apps/index'
import { Route as LayoutProjectsNewRouteImport } from './routes/_layout/projects/new'
import { Route as LayoutEventsNewRouteImport } from './routes/_layout/events/new'
import { Route as LayoutEventsSlugRouteImport } from './routes/_layout/events/$slug'
import { Route as LayoutBuildersAddRouteImport } from './routes/_layout/builders/add'
import { Route as LayoutBuildersAccountRouteImport } from './routes/_layout/builders/$account'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/_dashboard'
import { Route as LayoutProjectsNewIndexRouteImport } from './routes/_layout/projects/new.index'
import { Route as LayoutProjectsKindIndexRouteImport } from './routes/_layout/projects/$kind.index'
import { Route as LayoutAppsAccountIdIndexRouteImport } from './routes/_layout/apps/$accountId/index'
import { Route as LayoutProjectsNewKindRouteImport } from './routes/_layout/projects/new.$kind'
import { Route as LayoutProjectsKindSlugRouteImport } from './routes/_layout/projects/$kind.$slug'
import { Route as LayoutEventsSlugEditRouteImport } from './routes/_layout/events/$slug_.edit'
import { Route as LayoutBuildersAccountEditRouteImport } from './routes/_layout/builders/$account_.edit'
import { Route as LayoutAppsAccountIdGatewayIdRouteImport } from './routes/_layout/apps/$accountId/$gatewayId'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/_dashboard/settings'
import { Route as LayoutAuthenticatedDashboardProfileRouteImport } from './routes/_layout/_authenticated/_dashboard/profile'
import { Route as LayoutAuthenticatedDashboardDashboardRouteImport } from './routes/_layout/_authenticated/_dashboard/dashboard'
import { Route as LayoutAdminAdminDashboardRouteImport } from './routes/_layout/_admin/admin/dashboard'
import { Route as LayoutAuthenticatedDashboardSettingsIndexRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/index'
import { Route as LayoutAuthenticatedDashboardScopesIndexRouteImport } from './routes/_layout/_authenticated/_dashboard/scopes.index'
import { Route as LayoutAuthenticatedDashboardResultsIndexRouteImport } from './routes/_layout/_authenticated/_dashboard/results.index'
import { Route as LayoutAuthenticatedDashboardOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/_dashboard/organizations/index'
import { Route as LayoutAuthenticatedDashboardIdeasIndexRouteImport } from './routes/_layout/_authenticated/_dashboard/ideas.index'
import { Route as LayoutProjectsKindSlugEditRouteImport } from './routes/_layout/projects/$kind.$slug_.edit'
import { Route as LayoutAuthenticatedDashboardSettingsSecurityRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/security'
import { Route as LayoutAuthenticatedDashboardSettingsProfileRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/profile'
import { Route as LayoutAuthenticatedDashboardSettingsAuthMethodsRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/auth-methods'
import { Route as LayoutAuthenticatedDashboardSettingsApiKeysRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/api-keys'
import { Route as LayoutAuthenticatedDashboardOrganizationsNewRouteImport } from './routes/_layout/_authenticated/_dashboard/organizations/new'
import { Route as LayoutAuthenticatedDashboardOrganizationsSlugRouteImport } from './routes/_layout/_authenticated/_dashboard/organizations/$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillRoute = LayoutSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIronclawRoute = LayoutIronclawRouteImport.update({
  id: '/ironclaw',
  path: '/ironclaw',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutEventsIndexRoute = LayoutEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutBuildersIndexRoute = LayoutBuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsIndexRoute = LayoutAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsNewRoute = LayoutProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutEventsNewRoute = LayoutEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutEventsSlugRoute = LayoutEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutBuildersAddRoute = LayoutBuildersAddRouteImport.update({
  id: '/builders/add',
  path: '/builders/add',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildersAccountRoute = LayoutBuildersAccountRouteImport.update({
  id: '/builders/$account',
  path: '/builders/$account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutProjectsNewIndexRoute = LayoutProjectsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProjectsNewRoute,
} as any)
const LayoutProjectsKindIndexRoute = LayoutProjectsKindIndexRouteImport.update({
  id: '/$kind/',
  path: '/$kind/',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutAppsAccountIdIndexRoute =
  LayoutAppsAccountIdIndexRouteImport.update({
    id: '/apps/$accountId/',
    path: '/apps/$accountId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsNewKindRoute = LayoutProjectsNewKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => LayoutProjectsNewRoute,
} as any)
const LayoutProjectsKindSlugRoute = LayoutProjectsKindSlugRouteImport.update({
  id: '/$kind/$slug',
  path: '/$kind/$slug',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutEventsSlugEditRoute = LayoutEventsSlugEditRouteImport.update({
  id: '/$slug_/edit',
  path: '/$slug/edit',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutBuildersAccountEditRoute =
  LayoutBuildersAccountEditRouteImport.update({
    id: '/builders/$account_/edit',
    path: '/builders/$account/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAppsAccountIdGatewayIdRoute =
  LayoutAppsAccountIdGatewayIdRouteImport.update({
    id: '/apps/$accountId/$gatewayId',
    path: '/apps/$accountId/$gatewayId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardProfileRoute =
  LayoutAuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardDashboardRoute =
  LayoutAuthenticatedDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAdminAdminDashboardRoute =
  LayoutAdminAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsIndexRoute =
  LayoutAuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardScopesIndexRoute =
  LayoutAuthenticatedDashboardScopesIndexRouteImport.update({
    id: '/scopes/',
    path: '/scopes/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardResultsIndexRoute =
  LayoutAuthenticatedDashboardResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationsIndexRoute =
  LayoutAuthenticatedDashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardIdeasIndexRoute =
  LayoutAuthenticatedDashboardIdeasIndexRouteImport.update({
    id: '/ideas/',
    path: '/ideas/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutProjectsKindSlugEditRoute =
  LayoutProjectsKindSlugEditRouteImport.update({
    id: '/$kind/$slug_/edit',
    path: '/$kind/$slug/edit',
    getParentRoute: () => LayoutProjectsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsSecurityRoute =
  LayoutAuthenticatedDashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProfileRoute =
  LayoutAuthenticatedDashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAuthMethodsRoute =
  LayoutAuthenticatedDashboardSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsApiKeysRoute =
  LayoutAuthenticatedDashboardSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationsNewRoute =
  LayoutAuthenticatedDashboardOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationsSlugRoute =
  LayoutAuthenticatedDashboardOrganizationsSlugRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/events': typeof LayoutEventsRouteWithChildren
  '/ironclaw': typeof LayoutIronclawRoute
  '/login': typeof LayoutLoginRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/skill': typeof LayoutSkillRoute
  '/builders/$account': typeof LayoutBuildersAccountRoute
  '/builders/add': typeof LayoutBuildersAddRoute
  '/events/$slug': typeof LayoutEventsSlugRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/projects/new': typeof LayoutProjectsNewRouteWithChildren
  '/apps/': typeof LayoutAppsIndexRoute
  '/builders/': typeof LayoutBuildersIndexRoute
  '/events/': typeof LayoutEventsIndexRoute
  '/projects/': typeof LayoutProjectsIndexRoute
  '/admin/dashboard': typeof LayoutAdminAdminDashboardRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardDashboardRoute
  '/profile': typeof LayoutAuthenticatedDashboardProfileRoute
  '/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/builders/$account/edit': typeof LayoutBuildersAccountEditRoute
  '/events/$slug/edit': typeof LayoutEventsSlugEditRoute
  '/projects/$kind/$slug': typeof LayoutProjectsKindSlugRoute
  '/projects/new/$kind': typeof LayoutProjectsNewKindRoute
  '/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
  '/projects/$kind/': typeof LayoutProjectsKindIndexRoute
  '/projects/new/': typeof LayoutProjectsNewIndexRoute
  '/organizations/$slug': typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  '/settings/api-keys': typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  '/projects/$kind/$slug/edit': typeof LayoutProjectsKindSlugEditRoute
  '/ideas/': typeof LayoutAuthenticatedDashboardIdeasIndexRoute
  '/organizations/': typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
  '/results/': typeof LayoutAuthenticatedDashboardResultsIndexRoute
  '/scopes/': typeof LayoutAuthenticatedDashboardScopesIndexRoute
  '/settings/': typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/ironclaw': typeof LayoutIronclawRoute
  '/login': typeof LayoutLoginRoute
  '/skill': typeof LayoutSkillRoute
  '/builders/$account': typeof LayoutBuildersAccountRoute
  '/builders/add': typeof LayoutBuildersAddRoute
  '/events/$slug': typeof LayoutEventsSlugRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/apps': typeof LayoutAppsIndexRoute
  '/builders': typeof LayoutBuildersIndexRoute
  '/events': typeof LayoutEventsIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/admin/dashboard': typeof LayoutAdminAdminDashboardRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardDashboardRoute
  '/profile': typeof LayoutAuthenticatedDashboardProfileRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/builders/$account/edit': typeof LayoutBuildersAccountEditRoute
  '/events/$slug/edit': typeof LayoutEventsSlugEditRoute
  '/projects/$kind/$slug': typeof LayoutProjectsKindSlugRoute
  '/projects/new/$kind': typeof LayoutProjectsNewKindRoute
  '/apps/$accountId': typeof LayoutAppsAccountIdIndexRoute
  '/projects/$kind': typeof LayoutProjectsKindIndexRoute
  '/projects/new': typeof LayoutProjectsNewIndexRoute
  '/organizations/$slug': typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  '/settings/api-keys': typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  '/projects/$kind/$slug/edit': typeof LayoutProjectsKindSlugEditRoute
  '/ideas': typeof LayoutAuthenticatedDashboardIdeasIndexRoute
  '/organizations': typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
  '/results': typeof LayoutAuthenticatedDashboardResultsIndexRoute
  '/scopes': typeof LayoutAuthenticatedDashboardScopesIndexRoute
  '/settings': typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_admin': typeof LayoutAdminRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/events': typeof LayoutEventsRouteWithChildren
  '/_layout/ironclaw': typeof LayoutIronclawRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/skill': typeof LayoutSkillRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/_dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/builders/$account': typeof LayoutBuildersAccountRoute
  '/_layout/builders/add': typeof LayoutBuildersAddRoute
  '/_layout/events/$slug': typeof LayoutEventsSlugRoute
  '/_layout/events/new': typeof LayoutEventsNewRoute
  '/_layout/projects/new': typeof LayoutProjectsNewRouteWithChildren
  '/_layout/apps/': typeof LayoutAppsIndexRoute
  '/_layout/builders/': typeof LayoutBuildersIndexRoute
  '/_layout/events/': typeof LayoutEventsIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/_admin/admin/dashboard': typeof LayoutAdminAdminDashboardRoute
  '/_layout/_authenticated/_dashboard/dashboard': typeof LayoutAuthenticatedDashboardDashboardRoute
  '/_layout/_authenticated/_dashboard/profile': typeof LayoutAuthenticatedDashboardProfileRoute
  '/_layout/_authenticated/_dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/_layout/builders/$account_/edit': typeof LayoutBuildersAccountEditRoute
  '/_layout/events/$slug_/edit': typeof LayoutEventsSlugEditRoute
  '/_layout/projects/$kind/$slug': typeof LayoutProjectsKindSlugRoute
  '/_layout/projects/new/$kind': typeof LayoutProjectsNewKindRoute
  '/_layout/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
  '/_layout/projects/$kind/': typeof LayoutProjectsKindIndexRoute
  '/_layout/projects/new/': typeof LayoutProjectsNewIndexRoute
  '/_layout/_authenticated/_dashboard/organizations/$slug': typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  '/_layout/_authenticated/_dashboard/organizations/new': typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  '/_layout/_authenticated/_dashboard/settings/api-keys': typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  '/_layout/_authenticated/_dashboard/settings/auth-methods': typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  '/_layout/_authenticated/_dashboard/settings/profile': typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  '/_layout/_authenticated/_dashboard/settings/security': typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  '/_layout/projects/$kind/$slug_/edit': typeof LayoutProjectsKindSlugEditRoute
  '/_layout/_authenticated/_dashboard/ideas/': typeof LayoutAuthenticatedDashboardIdeasIndexRoute
  '/_layout/_authenticated/_dashboard/organizations/': typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
  '/_layout/_authenticated/_dashboard/results/': typeof LayoutAuthenticatedDashboardResultsIndexRoute
  '/_layout/_authenticated/_dashboard/scopes/': typeof LayoutAuthenticatedDashboardScopesIndexRoute
  '/_layout/_authenticated/_dashboard/settings/': typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/ironclaw'
    | '/login'
    | '/projects'
    | '/skill'
    | '/builders/$account'
    | '/builders/add'
    | '/events/$slug'
    | '/events/new'
    | '/projects/new'
    | '/apps/'
    | '/builders/'
    | '/events/'
    | '/projects/'
    | '/admin/dashboard'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/accept-invitation/$id'
    | '/apps/$accountId/$gatewayId'
    | '/builders/$account/edit'
    | '/events/$slug/edit'
    | '/projects/$kind/$slug'
    | '/projects/new/$kind'
    | '/apps/$accountId/'
    | '/projects/$kind/'
    | '/projects/new/'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/projects/$kind/$slug/edit'
    | '/ideas/'
    | '/organizations/'
    | '/results/'
    | '/scopes/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ironclaw'
    | '/login'
    | '/skill'
    | '/builders/$account'
    | '/builders/add'
    | '/events/$slug'
    | '/events/new'
    | '/apps'
    | '/builders'
    | '/events'
    | '/projects'
    | '/admin/dashboard'
    | '/dashboard'
    | '/profile'
    | '/accept-invitation/$id'
    | '/apps/$accountId/$gatewayId'
    | '/builders/$account/edit'
    | '/events/$slug/edit'
    | '/projects/$kind/$slug'
    | '/projects/new/$kind'
    | '/apps/$accountId'
    | '/projects/$kind'
    | '/projects/new'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/projects/$kind/$slug/edit'
    | '/ideas'
    | '/organizations'
    | '/results'
    | '/scopes'
    | '/settings'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_admin'
    | '/_layout/_authenticated'
    | '/_layout/about'
    | '/_layout/events'
    | '/_layout/ironclaw'
    | '/_layout/login'
    | '/_layout/projects'
    | '/_layout/skill'
    | '/_layout/'
    | '/_layout/_authenticated/_dashboard'
    | '/_layout/builders/$account'
    | '/_layout/builders/add'
    | '/_layout/events/$slug'
    | '/_layout/events/new'
    | '/_layout/projects/new'
    | '/_layout/apps/'
    | '/_layout/builders/'
    | '/_layout/events/'
    | '/_layout/projects/'
    | '/_layout/_admin/admin/dashboard'
    | '/_layout/_authenticated/_dashboard/dashboard'
    | '/_layout/_authenticated/_dashboard/profile'
    | '/_layout/_authenticated/_dashboard/settings'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/apps/$accountId/$gatewayId'
    | '/_layout/builders/$account_/edit'
    | '/_layout/events/$slug_/edit'
    | '/_layout/projects/$kind/$slug'
    | '/_layout/projects/new/$kind'
    | '/_layout/apps/$accountId/'
    | '/_layout/projects/$kind/'
    | '/_layout/projects/new/'
    | '/_layout/_authenticated/_dashboard/organizations/$slug'
    | '/_layout/_authenticated/_dashboard/organizations/new'
    | '/_layout/_authenticated/_dashboard/settings/api-keys'
    | '/_layout/_authenticated/_dashboard/settings/auth-methods'
    | '/_layout/_authenticated/_dashboard/settings/profile'
    | '/_layout/_authenticated/_dashboard/settings/security'
    | '/_layout/projects/$kind/$slug_/edit'
    | '/_layout/_authenticated/_dashboard/ideas/'
    | '/_layout/_authenticated/_dashboard/organizations/'
    | '/_layout/_authenticated/_dashboard/results/'
    | '/_layout/_authenticated/_dashboard/scopes/'
    | '/_layout/_authenticated/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skill': {
      id: '/_layout/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof LayoutSkillRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ironclaw': {
      id: '/_layout/ironclaw'
      path: '/ironclaw'
      fullPath: '/ironclaw'
      preLoaderRoute: typeof LayoutIronclawRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events': {
      id: '/_layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_admin': {
      id: '/_layout/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/events/': {
      id: '/_layout/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof LayoutEventsIndexRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/builders/': {
      id: '/_layout/builders/'
      path: '/builders'
      fullPath: '/builders/'
      preLoaderRoute: typeof LayoutBuildersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/': {
      id: '/_layout/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof LayoutAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/new': {
      id: '/_layout/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof LayoutProjectsNewRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/events/new': {
      id: '/_layout/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof LayoutEventsNewRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/events/$slug': {
      id: '/_layout/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof LayoutEventsSlugRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/builders/add': {
      id: '/_layout/builders/add'
      path: '/builders/add'
      fullPath: '/builders/add'
      preLoaderRoute: typeof LayoutBuildersAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/builders/$account': {
      id: '/_layout/builders/$account'
      path: '/builders/$account'
      fullPath: '/builders/$account'
      preLoaderRoute: typeof LayoutBuildersAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/_dashboard': {
      id: '/_layout/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/projects/new/': {
      id: '/_layout/projects/new/'
      path: '/'
      fullPath: '/projects/new/'
      preLoaderRoute: typeof LayoutProjectsNewIndexRouteImport
      parentRoute: typeof LayoutProjectsNewRoute
    }
    '/_layout/projects/$kind/': {
      id: '/_layout/projects/$kind/'
      path: '/$kind'
      fullPath: '/projects/$kind/'
      preLoaderRoute: typeof LayoutProjectsKindIndexRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/apps/$accountId/': {
      id: '/_layout/apps/$accountId/'
      path: '/apps/$accountId'
      fullPath: '/apps/$accountId/'
      preLoaderRoute: typeof LayoutAppsAccountIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/new/$kind': {
      id: '/_layout/projects/new/$kind'
      path: '/$kind'
      fullPath: '/projects/new/$kind'
      preLoaderRoute: typeof LayoutProjectsNewKindRouteImport
      parentRoute: typeof LayoutProjectsNewRoute
    }
    '/_layout/projects/$kind/$slug': {
      id: '/_layout/projects/$kind/$slug'
      path: '/$kind/$slug'
      fullPath: '/projects/$kind/$slug'
      preLoaderRoute: typeof LayoutProjectsKindSlugRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/events/$slug_/edit': {
      id: '/_layout/events/$slug_/edit'
      path: '/$slug/edit'
      fullPath: '/events/$slug/edit'
      preLoaderRoute: typeof LayoutEventsSlugEditRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/builders/$account_/edit': {
      id: '/_layout/builders/$account_/edit'
      path: '/builders/$account/edit'
      fullPath: '/builders/$account/edit'
      preLoaderRoute: typeof LayoutBuildersAccountEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/$accountId/$gatewayId': {
      id: '/_layout/apps/$accountId/$gatewayId'
      path: '/apps/$accountId/$gatewayId'
      fullPath: '/apps/$accountId/$gatewayId'
      preLoaderRoute: typeof LayoutAppsAccountIdGatewayIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_dashboard/settings': {
      id: '/_layout/_authenticated/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/profile': {
      id: '/_layout/_authenticated/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/dashboard': {
      id: '/_layout/_authenticated/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_admin/admin/dashboard': {
      id: '/_layout/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof LayoutAdminAdminDashboardRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/_authenticated/_dashboard/settings/': {
      id: '/_layout/_authenticated/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/scopes/': {
      id: '/_layout/_authenticated/_dashboard/scopes/'
      path: '/scopes'
      fullPath: '/scopes/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardScopesIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/results/': {
      id: '/_layout/_authenticated/_dashboard/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardResultsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/organizations/': {
      id: '/_layout/_authenticated/_dashboard/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/ideas/': {
      id: '/_layout/_authenticated/_dashboard/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIdeasIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/projects/$kind/$slug_/edit': {
      id: '/_layout/projects/$kind/$slug_/edit'
      path: '/$kind/$slug/edit'
      fullPath: '/projects/$kind/$slug/edit'
      preLoaderRoute: typeof LayoutProjectsKindSlugEditRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/_authenticated/_dashboard/settings/security': {
      id: '/_layout/_authenticated/_dashboard/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/settings/profile': {
      id: '/_layout/_authenticated/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/settings/auth-methods': {
      id: '/_layout/_authenticated/_dashboard/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/settings/api-keys': {
      id: '/_layout/_authenticated/_dashboard/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsApiKeysRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/organizations/new': {
      id: '/_layout/_authenticated/_dashboard/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/organizations/$slug': {
      id: '/_layout/_authenticated/_dashboard/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAdminDashboardRoute: typeof LayoutAdminAdminDashboardRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAdminDashboardRoute: LayoutAdminAdminDashboardRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsApiKeysRoute: typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  LayoutAuthenticatedDashboardSettingsAuthMethodsRoute: typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  LayoutAuthenticatedDashboardSettingsProfileRoute: typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  LayoutAuthenticatedDashboardSettingsSecurityRoute: typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  LayoutAuthenticatedDashboardSettingsIndexRoute: typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsApiKeysRoute:
      LayoutAuthenticatedDashboardSettingsApiKeysRoute,
    LayoutAuthenticatedDashboardSettingsAuthMethodsRoute:
      LayoutAuthenticatedDashboardSettingsAuthMethodsRoute,
    LayoutAuthenticatedDashboardSettingsProfileRoute:
      LayoutAuthenticatedDashboardSettingsProfileRoute,
    LayoutAuthenticatedDashboardSettingsSecurityRoute:
      LayoutAuthenticatedDashboardSettingsSecurityRoute,
    LayoutAuthenticatedDashboardSettingsIndexRoute:
      LayoutAuthenticatedDashboardSettingsIndexRoute,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardDashboardRoute: typeof LayoutAuthenticatedDashboardDashboardRoute
  LayoutAuthenticatedDashboardProfileRoute: typeof LayoutAuthenticatedDashboardProfileRoute
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardOrganizationsSlugRoute: typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  LayoutAuthenticatedDashboardOrganizationsNewRoute: typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  LayoutAuthenticatedDashboardIdeasIndexRoute: typeof LayoutAuthenticatedDashboardIdeasIndexRoute
  LayoutAuthenticatedDashboardOrganizationsIndexRoute: typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
  LayoutAuthenticatedDashboardResultsIndexRoute: typeof LayoutAuthenticatedDashboardResultsIndexRoute
  LayoutAuthenticatedDashboardScopesIndexRoute: typeof LayoutAuthenticatedDashboardScopesIndexRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardDashboardRoute:
      LayoutAuthenticatedDashboardDashboardRoute,
    LayoutAuthenticatedDashboardProfileRoute:
      LayoutAuthenticatedDashboardProfileRoute,
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardOrganizationsSlugRoute:
      LayoutAuthenticatedDashboardOrganizationsSlugRoute,
    LayoutAuthenticatedDashboardOrganizationsNewRoute:
      LayoutAuthenticatedDashboardOrganizationsNewRoute,
    LayoutAuthenticatedDashboardIdeasIndexRoute:
      LayoutAuthenticatedDashboardIdeasIndexRoute,
    LayoutAuthenticatedDashboardOrganizationsIndexRoute:
      LayoutAuthenticatedDashboardOrganizationsIndexRoute,
    LayoutAuthenticatedDashboardResultsIndexRoute:
      LayoutAuthenticatedDashboardResultsIndexRoute,
    LayoutAuthenticatedDashboardScopesIndexRoute:
      LayoutAuthenticatedDashboardScopesIndexRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutEventsRouteChildren {
  LayoutEventsSlugRoute: typeof LayoutEventsSlugRoute
  LayoutEventsNewRoute: typeof LayoutEventsNewRoute
  LayoutEventsIndexRoute: typeof LayoutEventsIndexRoute
  LayoutEventsSlugEditRoute: typeof LayoutEventsSlugEditRoute
}

const LayoutEventsRouteChildren: LayoutEventsRouteChildren = {
  LayoutEventsSlugRoute: LayoutEventsSlugRoute,
  LayoutEventsNewRoute: LayoutEventsNewRoute,
  LayoutEventsIndexRoute: LayoutEventsIndexRoute,
  LayoutEventsSlugEditRoute: LayoutEventsSlugEditRoute,
}

const LayoutEventsRouteWithChildren = LayoutEventsRoute._addFileChildren(
  LayoutEventsRouteChildren,
)

interface LayoutProjectsNewRouteChildren {
  LayoutProjectsNewKindRoute: typeof LayoutProjectsNewKindRoute
  LayoutProjectsNewIndexRoute: typeof LayoutProjectsNewIndexRoute
}

const LayoutProjectsNewRouteChildren: LayoutProjectsNewRouteChildren = {
  LayoutProjectsNewKindRoute: LayoutProjectsNewKindRoute,
  LayoutProjectsNewIndexRoute: LayoutProjectsNewIndexRoute,
}

const LayoutProjectsNewRouteWithChildren =
  LayoutProjectsNewRoute._addFileChildren(LayoutProjectsNewRouteChildren)

interface LayoutProjectsRouteChildren {
  LayoutProjectsNewRoute: typeof LayoutProjectsNewRouteWithChildren
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutProjectsKindSlugRoute: typeof LayoutProjectsKindSlugRoute
  LayoutProjectsKindIndexRoute: typeof LayoutProjectsKindIndexRoute
  LayoutProjectsKindSlugEditRoute: typeof LayoutProjectsKindSlugEditRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsNewRoute: LayoutProjectsNewRouteWithChildren,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutProjectsKindSlugRoute: LayoutProjectsKindSlugRoute,
  LayoutProjectsKindIndexRoute: LayoutProjectsKindIndexRoute,
  LayoutProjectsKindSlugEditRoute: LayoutProjectsKindSlugEditRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutEventsRoute: typeof LayoutEventsRouteWithChildren
  LayoutIronclawRoute: typeof LayoutIronclawRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutSkillRoute: typeof LayoutSkillRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBuildersAccountRoute: typeof LayoutBuildersAccountRoute
  LayoutBuildersAddRoute: typeof LayoutBuildersAddRoute
  LayoutAppsIndexRoute: typeof LayoutAppsIndexRoute
  LayoutBuildersIndexRoute: typeof LayoutBuildersIndexRoute
  LayoutAppsAccountIdGatewayIdRoute: typeof LayoutAppsAccountIdGatewayIdRoute
  LayoutBuildersAccountEditRoute: typeof LayoutBuildersAccountEditRoute
  LayoutAppsAccountIdIndexRoute: typeof LayoutAppsAccountIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutEventsRoute: LayoutEventsRouteWithChildren,
  LayoutIronclawRoute: LayoutIronclawRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutSkillRoute: LayoutSkillRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBuildersAccountRoute: LayoutBuildersAccountRoute,
  LayoutBuildersAddRoute: LayoutBuildersAddRoute,
  LayoutAppsIndexRoute: LayoutAppsIndexRoute,
  LayoutBuildersIndexRoute: LayoutBuildersIndexRoute,
  LayoutAppsAccountIdGatewayIdRoute: LayoutAppsAccountIdGatewayIdRoute,
  LayoutBuildersAccountEditRoute: LayoutBuildersAccountEditRoute,
  LayoutAppsAccountIdIndexRoute: LayoutAppsAccountIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
